SELECT CASE MAJOR_DIV_CODE WHEN 'OTH'
    THEN 'ACTIVITIES NOT ADEQUATELY DEFINED' 
    ELSE MAJOR_BUSINESS END AS "MAJOR BUSINESS", 
    MAJOR_DIV_CODE,
    ORG_CAT_ENT_CD,
    CASE MAJOR_DIV_CODE WHEN 'OTH'
    THEN 'ACTIVITIES NOT ADEQUATELY DEFINED' 
    ELSE MAJOR_BUSINESS END AS "DUP MAJOR BUSINESS"
FROM icrs_interface.vw_all_entity
WHERE org_last_sta_cd NOT IN  ('DIS', 'DRF', 'DRG', 'INACT', 'SUB', 'CAN')
AND org_cat_ent_cd IS NOT NULL
AND ORG_INCORP_DT < SYSDATE